In [18]:
import numpy as np

D = np.matrix([[5, 2], [8, 1]])

u, svals, pcs = np.linalg.svd(D, full_matrices=False)
print ("U   :  ",u)
print ("Svals   :  ",svals)
print ("PCS   :  ",pcs)

U   :   [[-0.55049101 -0.83484109]
 [-0.83484109  0.55049101]]
Svals   :   [ 9.62780549  1.14252412]
PCS   :   [[-0.97957772 -0.20106587]
 [ 0.20106587 -0.97957772]]


In [37]:
import numpy as np

D = np.matrix([[5, 2], [8, 1]])
print (D.mean())
D = D - D.mean(0)
cov = np.cov(D)
print (D)
print ("-------------------------")
print (cov)
print ("-------------------------")
print (cov * D)

4.0
[[-1.5  0.5]
 [ 1.5 -0.5]]
-------------------------
[[ 2. -2.]
 [-2.  2.]]
-------------------------
[[-6.  2.]
 [ 6. -2.]]


In [10]:
import numpy as np
C = np.matrix([[0, 0],[0,2]])
D = np.matrix([[0], [5]])
print(D)
print(C[1])
C*D

[[0]
 [5]]
[[0 2]]


matrix([[ 0],
        [10]])